name: Analyze Digikala with GPT-J
on:
  workflow_dispatch:
  push:
    paths:
      - "inputs/**"

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy xlsxwriter transformers torch requests openpyxl

      - name: Detect input file
        id: vars
        run: |
          FILE=$(ls inputs/*.xlsx | head -n 1)
          echo "file=$FILE" >> $GITHUB_OUTPUT
          BASENAME=$(basename "$FILE")
          echo "basename=$BASENAME" >> $GITHUB_OUTPUT

      - name: Run analysis
        env:
          HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
        run: |
          mkdir -p outputs
          python tools/analyze_digikala.py --input "${{ steps.vars.outputs.file }}" --output "outputs/${{ steps.vars.outputs.basename }}" --gpt-scope "all"

      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .
